use std::path::PathBuf;

use crate::model::{PlaylistColumn, PlaylistId};
use crate::soulseek::{SoulseekFilterField, SoulseekFormat, SoulseekScope};

#[derive(Clone, Debug, PartialEq)]
pub enum Action {
    None,
    Quit,
    TogglePlay,
    Stop,
    Previous,
    Next,
    SeekRelative(i64),
    SeekFraction(f64),
    VolumeRelative(f32),
    SetVolume(f32),
    CyclePlaybackOrder,
    SelectPlaylist(usize),
    SelectAlbumRow(usize),
    SelectPlaylistRow(usize),
    NewPlaylist,
    BeginRenamePlaylist,
    RenamePlaylist(PlaylistId, String),
    ClosePlaylist,
    MoveSelection(i32),
    PageSelection(i32),
    ActivateSelection,
    RemoveSelection,
    AddPaths(Vec<PathBuf>),
    AddFromClipboard,
    OpenFiles,
    OpenFolder,
    ToggleHelp,
    OpenMenu(usize),
    ActivateMenuItem(usize),
    OverlayMove(i32),
    OverlayActivate,
    TextInput(char),
    PasteText(String),
    TextBackspace,
    PickerChooseCurrent,
    CloseOverlay,
    FocusNext(bool),
    RetryAudio,
    RescanLibrary,
    BeginConnect,
    DisconnectServer,
    SubmitConnect,
    SubmitPair,
    BeginSoulseek,
    SoulseekFold(bool),
    SoulseekDownload(SoulseekScope),
    SoulseekHide(SoulseekScope),
    SoulseekSetFormat(SoulseekFormat),
    SoulseekCycleFormat(i32),
    SoulseekToggleFreeSlot,
    SoulseekCycleFilter(SoulseekFilterField),
    BeginFilter,
    ClearFilter,
    ToggleMark,
    TogglePlaylistRow(usize),
    ExtendSelection(i32),
    MovePlaylistItems(i32),
    SortPlaylist(PlaylistColumn),
    OpenListContext {
        row: Option<usize>,
        x: Option<u16>,
        y: Option<u16>,
    },
    QueueSelection,
    ClearQueue,
    ToggleStopAfterCurrent,
    ShowProperties,
    OpenContainingFolder,
    AddSelectionToPlaylist(usize),
    ScanReplayGain,
    OpenSettings,
    SettingsAdjust(i32),
}
